# Local Environment Configuration

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /api

# Spring configuration
spring:
  application:
    name: story-teller-be

  # Database configuration
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/localdb
    username: yasarku
    password: 6116131
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: story-teller

# Logging configuration
logging:
  level:
    root: INFO
    com.yasarku: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: ./logs/application-local.log

# Application-specific properties
app:
  environment: local
  feature-flags:
    enable-swagger: true
  file-storage:
    base-path: ./local-storage
