# Test Environment Configuration

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /api

# Spring configuration
spring:
  application:
    name: story-teller-be
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  # JPA/Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging configuration
logging:
  level:
    root: INFO
    com.yasarku: INFO
    org.hibernate.SQL: INFO

# Application-specific properties
app:
  environment: test
  feature-flags:
    enable-swagger: false