name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/story-teller-be:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Deploy to Minikube via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MINIKUBE_HOST }}
          username: ${{ secrets.MINIKUBE_USER }}
          key: ${{ secrets.MINIKUBE_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull ${{ env.IMAGE_NAME }}
            
            echo "Applying Kubernetes deployment..."
            kubectl apply -f ~/app/k8s/deployment.yaml
